### ISSUE TITLE
Locomotion

### ISSUE THREAD

**Issue by MrRekrow** [Ess-Ka/EsskaAV3Obfuscator#12]
I have used this script many times before without any problems, but on my current model I'm having odd results. After using this script and uploading my locomotion for the standing blendtree is freezing up, everything else is okay within the base layer. When I run I like skate along the ground instead of stepping. If I replace my locomotion/base layer with the original it works correctly. Additionally, my avatar is uploaded only for pc users, and quest users now see my (fallback) in ground after using obfuscator script. The problem is most likely with the model and or layers. My standing/running/crouching/prone are all GOGO 5.0 blendtrees, my jumping and falling is the default VRC's. Sorry, for lack of information.

**Comment by MrRekrow** [comment]
Hello. I've solved the issue. I had taken some of the proxy animations that vrc utilizes and put them in folders in my project. This seemed to had allowed them to get effected from the script.

**Comment by Ess-Ka** [comment]
Hello MrRekrow
The Obfuscator excludes the proxy animations from obfuscation:
![grafik](https://github.com/Ess-Ka/EsskaAV3Obfuscator/assets/84975839/1458999c-9979-4e84-b65b-b2838c055027)

Moving the proxy animation into your own folder changed the path and because of that, the proxy anims was obfuscated. This caused the animations to break.
